/**
 * Default fallback data for courses that don't have
 * course-specific curriculum or assessment data.
 * These are overridden when a course has its own data.
 */

import type { AssessmentCertificationData, CurriculumData } from "./CoursesCardData";

export const defaultAssessmentCertification: AssessmentCertificationData = {
  assessmentCards: [
    {
      id: 0,
      title: "Weekly Assignments",
      description: "Hands-on tasks after every concept to reinforce real-world understanding",
      features: ["Weekly Challenges", "Automated Evaluation", "Progress Tracking"],
      backContent: {
        points: [
          "Concept-based coding challenges",
          "Real-world problem solving tasks",
          "Peer review and feedback",
          "Performance benchmarking",
          "Knowledge retention quizzes",
        ],
        frequency: "Every Week",
        weightage: "20% of final grade",
      },
    },
    {
      id: 1,
      title: "Module Assessments",
      description: "End-of-module tests to validate comprehensive understanding",
      features: ["Practical Challenges", "Scenario-Based Tests", "Detailed Feedback"],
      backContent: {
        points: [
          "Module-end comprehensive tests",
          "Practical coding challenges",
          "Scenario-based problem solving",
          "Time-bound assessments",
          "Personalized improvement reports",
        ],
        frequency: "After Each Module",
        weightage: "30% of final grade",
      },
    },
    {
      id: 2,
      title: "Project Evaluations",
      description: "In-depth review of real-world projects with expert mentor feedback",
      features: ["Architecture Review", "Code Quality Check", "Deployment Validation"],
      backContent: {
        points: [
          "Full project architecture evaluation",
          "Code quality and best practices review",
          "Deployment and scalability assessment",
          "Documentation quality check",
          "Live demo and presentation scoring",
        ],
        frequency: "Per Project",
        weightage: "40% of final grade",
      },
    },
    {
      id: 3,
      title: "Certification Benefits",
      description: "Industry-recognized certificate with global validity and hiring partner access",
      features: ["Industry Recognized", "Global Validity", "Hiring Partner Access"],
      backContent: {
        points: [
          "Industry-recognized certificate",
          "Global recognition and validity",
          "Hiring partner acceptance",
          "Verified by industry experts",
          "Includes digital badge for LinkedIn",
        ],
        frequency: "Program Completion",
        weightage: "Official Certification",
      },
    },
  ],
  certificateData: {
    title: "Industry-Recognized Certification",
    description:
      "Our certificate validates your skills and demonstrates your competency to employers worldwide.",
    benefits: [
      "Industry-recognized certificate",
      "Global recognition and validity",
      "Hiring partner acceptance",
      "Verified by industry experts",
      "Includes digital badge for LinkedIn",
      "Career network access",
    ],
    certificateDetails: {
      title: "Certificate of Completion",
      subtitle: "Professional Development Program",
      subSubtitle: "Covering Industry Tools, Best Practices, Real-World Projects, and Career-Ready Skills.",
      rating: 5,
    },
  },
};

export const defaultCurriculum: CurriculumData = {
  title: "Comprehensive Curriculum",
  description: "6–8 Months • 500–600 Hours",
  phases: [
    {
      id: 0,
      title: "Phase 1",
      subtitle: "Fundamentals & Core Concepts",
      icon: "BookOpen",
      duration: "6-8 Weeks",
      gradient: "from-blue-500 to-indigo-600",
      bgColor: "bg-gradient-to-br from-blue-50 to-indigo-50",
      borderColor: "border-blue-200",
      topics: [
        {
          title: "Core Fundamentals (3-4 Weeks)",
          color: "blue-500",
          items: [
            "Environment setup and toolchain",
            "Core language / framework syntax",
            "Data structures and algorithms",
            "Version control with Git & GitHub",
            "Debugging and problem solving",
            "Best practices and coding standards",
          ],
        },
        {
          title: "Applied Concepts (3-4 Weeks)",
          color: "indigo-500",
          items: [
            "Applied project architecture",
            "Testing and validation",
            "Performance optimization basics",
            "Documentation practices",
            "Code reviews and refactoring",
            "Security fundamentals",
          ],
        },
      ],
      projects: [
        { title: "Mini Project:", description: "Build a foundational application from scratch", color: "blue" },
        { title: "Mini Project:", description: "Implement core concepts in a practical scenario", color: "indigo" },
      ],
    },
    {
      id: 1,
      title: "Phase 2",
      subtitle: "Intermediate Development Skills",
      icon: "Code",
      duration: "6-8 Weeks",
      gradient: "from-green-500 to-emerald-600",
      bgColor: "bg-gradient-to-br from-green-50 to-emerald-50",
      borderColor: "border-green-200",
      topics: [
        {
          title: "Intermediate Patterns (3-4 Weeks)",
          color: "green-500",
          items: [
            "Design patterns and architecture",
            "REST API integration",
            "Authentication and authorization",
            "Database management",
            "Error handling strategies",
            "State management",
          ],
        },
        {
          title: "Real-World Integration (3-4 Weeks)",
          color: "emerald-500",
          items: [
            "Third-party API integration",
            "Cloud service basics",
            "File handling and uploads",
            "Email and notification systems",
            "Logging and monitoring",
            "Performance profiling",
          ],
        },
      ],
      projects: [
        { title: "Project 1:", description: "Full-featured CRUD application with authentication", color: "green" },
        { title: "Project 2:", description: "API-driven application with real-world integrations", color: "emerald" },
      ],
    },
    {
      id: 2,
      title: "Phase 3",
      subtitle: "Advanced Topics & Specialization",
      icon: "Zap",
      duration: "8-10 Weeks",
      gradient: "from-purple-500 to-violet-600",
      bgColor: "bg-gradient-to-br from-purple-50 to-violet-50",
      borderColor: "border-purple-200",
      topics: [
        {
          title: "Advanced Architecture (4-5 Weeks)",
          color: "purple-500",
          items: [
            "Microservices architecture",
            "Containerization with Docker",
            "Cloud deployment strategies",
            "CI/CD pipeline setup",
            "Scalability and load balancing",
            "Security best practices",
          ],
        },
        {
          title: "AI & Modern Tooling (4-5 Weeks)",
          color: "violet-500",
          items: [
            "AI/ML integration basics",
            "Modern tooling and automation",
            "Infrastructure as Code",
            "Monitoring and observability",
            "Cost optimization",
            "Production readiness",
          ],
        },
      ],
      projects: [
        { title: "Project 1:", description: "Microservices-based scalable application", color: "purple" },
        { title: "Project 2:", description: "Cloud-deployed production application with CI/CD", color: "violet" },
      ],
    },
    {
      id: 3,
      title: "Phase 4",
      subtitle: "Capstone Projects & Career Preparation",
      icon: "Rocket",
      duration: "4-6 Weeks",
      gradient: "from-orange-500 to-amber-600",
      bgColor: "bg-gradient-to-br from-orange-50 to-amber-50",
      borderColor: "border-orange-200",
      topics: [
        {
          title: "Capstone Development (2-3 Weeks)",
          color: "orange-500",
          items: [
            "End-to-end project development",
            "Real business problem solving",
            "Full deployment and production setup",
            "Documentation and presentation",
            "Portfolio building and GitHub profile",
            "Project showcase preparation",
          ],
        },
        {
          title: "Interview Preparation (2-3 Weeks)",
          color: "amber-500",
          items: [
            "Technical interview mock sessions",
            "System design interview practice",
            "Resume and LinkedIn optimization",
            "Salary negotiation strategies",
            "Top company interview patterns",
            "Placement support and referrals",
          ],
        },
      ],
      projects: [
        { title: "Capstone Project:", description: "Production-ready application solving a real business problem", color: "orange" },
        { title: "Interview Outcome:", description: "Crack interviews at top tech companies worldwide", color: "amber" },
      ],
    },
  ],
  projects: [
    {
      id: 0,
      title: "Real-World Application #1",
      description: "End-to-end application built with industry best practices and production-ready architecture",
      icon: "Code",
      gradient: "from-blue-500 to-cyan-500",
      bgColor: "bg-gradient-to-br from-blue-50 to-cyan-50",
      borderColor: "border-blue-200",
      tags: ["Full Stack", "REST APIs", "Database", "Cloud", "CI/CD"],
    },
    {
      id: 1,
      title: "AI-Integrated Application",
      description: "Modern application with AI/ML capabilities integrated for intelligent features",
      icon: "Brain",
      gradient: "from-purple-500 to-pink-500",
      bgColor: "bg-gradient-to-br from-purple-50 to-pink-50",
      borderColor: "border-purple-200",
      tags: ["AI Integration", "Machine Learning", "APIs", "Automation"],
    },
    {
      id: 2,
      title: "Cloud-Deployed Platform",
      description: "Scalable, cloud-native platform deployed on AWS/GCP with monitoring and analytics",
      icon: "Cloud",
      gradient: "from-green-500 to-emerald-500",
      bgColor: "bg-gradient-to-br from-green-50 to-emerald-50",
      borderColor: "border-green-200",
      tags: ["AWS", "Docker", "Kubernetes", "Monitoring", "Scalable"],
    },
    {
      id: 3,
      title: "Enterprise-Grade Capstone",
      description: "Production-ready enterprise application solving a real business problem with full documentation",
      icon: "Building",
      gradient: "from-orange-500 to-amber-500",
      bgColor: "bg-gradient-to-br from-orange-50 to-amber-50",
      borderColor: "border-orange-200",
      tags: ["Enterprise", "Security", "Performance", "Documentation", "Deployment"],
    },
  ],
  techStack: [
    {
      category: "Core Technologies",
      icon: "Code",
      borderColor: "border-blue-200",
      bgColor: "bg-gradient-to-r from-blue-50 to-indigo-50",
      technologies: [
        { label: "Python", iconSrc: "/DAT1.webp" },
        { label: "JavaScript", iconSrc: "/FSE1.webp" },
        { label: "TypeScript", iconSrc: "/FSE2.webp" },
        { label: "Git", iconSrc: "/DAT3.webp" },
        { label: "Docker", iconSrc: "/DD4.webp" },
        { label: "Linux", iconSrc: "/DevOps3.webp" },
      ],
    },
    {
      category: "Cloud & DevOps",
      icon: "Cloud",
      borderColor: "border-green-200",
      bgColor: "bg-gradient-to-r from-green-50 to-emerald-50",
      technologies: [
        { label: "AWS", iconSrc: "/CP1.webp" },
        { label: "Google Cloud", iconSrc: "/CP2.webp" },
        { label: "Azure", iconSrc: "/CP3.webp" },
        { label: "Kubernetes", iconSrc: "/DP3.webp" },
        { label: "Terraform", iconSrc: "/DevOps5.webp" },
        { label: "GitHub Actions", iconSrc: "/DevOps6.webp" },
      ],
    },
  ],
  careerOutcomes: [
    {
      title: "Software Developer",
      salary: "$75k–$130k",
      icon: "Code",
      gradient: "from-blue-500 to-cyan-500",
      bgColor: "bg-gradient-to-br from-blue-50 to-cyan-50",
      borderColor: "border-blue-200",
      description: "Build production-grade applications and systems at top tech companies.",
    },
    {
      title: "Senior Engineer",
      salary: "$100k–$160k",
      icon: "Zap",
      gradient: "from-purple-500 to-pink-500",
      bgColor: "bg-gradient-to-br from-purple-50 to-pink-50",
      borderColor: "border-purple-200",
      description: "Lead technical teams and architect scalable solutions for enterprise clients.",
    },
    {
      title: "Tech Lead / Architect",
      salary: "$130k–$200k",
      icon: "Star",
      gradient: "from-orange-500 to-amber-500",
      bgColor: "bg-gradient-to-br from-orange-50 to-amber-50",
      borderColor: "border-orange-200",
      description: "Drive technology decisions and mentor teams at industry-leading organizations.",
    },
  ],
  capstoneData: {
    title: "Capstone Development",
    icon: "FileText",
    bgColor: "bg-white",
    borderColor: "border-orange-200",
    projects: ["End-to-End Application", "Real Business Problem", "Cloud Deployment"],
    outcome: "Production-ready application with full DevOps pipeline and documentation",
  },
  interviewPrep: {
    title: "Interview Preparation",
    icon: "Users",
    bgColor: "bg-white",
    borderColor: "border-orange-200",
    technical: ["Data Structures", "System Design", "Coding Challenges", "Architecture Patterns"],
    career: ["Resume + LinkedIn", "Mock Interviews", "Salary Negotiation"],
    outcome: "Crack technical interviews at top tech companies worldwide",
  },
};
