server {
    listen 80;
    server_name
        origin-api.realtutorialhub.com
        origin-api.skillupitacademy.com
        origin-api.skillhubcore.in
        api.realtutorialhub.com
        api.skillupitacademy.com
        api.skillhubcore.in;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name origin-api.realtutorialhub.com api.realtutorialhub.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://api-server:3000;
    }
}

server {
    listen 443 ssl http2;
    server_name origin-api.skillupitacademy.com api.skillupitacademy.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://api-server:3000;
    }
}

server {
    listen 443 ssl http2;
    server_name origin-api.skillhubcore.in api.skillhubcore.in;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://skillhubcore-service:3000;
    }
}
