server {
    listen 80;
    server_name
        user.realtutorialhub.com
        admin.realtutorialhub.com
        user.skillupitacademy.com
        admin.skillupitacademy.com
        faculty.skillupitacademy.com
        quiz.skillhubcore.in
        tutorial.skillhubcore.in
        placement.skillhubcore.in
        admin.skillhubcore.in;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name user.realtutorialhub.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://realtutorialhub-web:3003;
    }
}

server {
    listen 443 ssl http2;
    server_name admin.realtutorialhub.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://realtutorialhub-admin:3002;
    }
}

server {
    listen 443 ssl http2;
    server_name user.skillupitacademy.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://skillup-web:3004;
    }
}

server {
    listen 443 ssl http2;
    server_name admin.skillupitacademy.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://skillup-admin:3005;
    }
}

server {
    listen 443 ssl http2;
    server_name faculty.skillupitacademy.com;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://faculty-app:3006;
    }
}
