server {
    listen 8080;
    server_name _;

    access_log off;

    location = /nginx_status {
        stub_status;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        allow 10.0.0.0/8;
        deny all;
    }
}
