server {
    listen 443 ssl http2;
    server_name quiz.skillhubcore.in origin-quiz.skillhubcore.in;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://realtutorialhub-quiz:3001;
    }
}

server {
    listen 443 ssl http2;
    server_name tutorial.skillhubcore.in origin-tutorial.skillhubcore.in;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://realtutorialhub-web:3003;
    }
}

server {
    listen 443 ssl http2;
    server_name placement.skillhubcore.in origin-placement.skillhubcore.in;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://skillhub-placement:3008;
    }
}

server {
    listen 443 ssl http2;
    server_name admin.skillhubcore.in origin-admin.skillhubcore.in;
    include /etc/nginx/snippets/ssl-origin.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://skillhubcore-admin:3000;
    }
}
