// create-test-users-drizzle.ts
import { db as rthDb } from './packages/db-rth/src/index';
import { db as skillupDb } from './packages/db-skillup/src/index';
import { users, userProfiles, roles, userRoles } from './packages/db-rth/src/index';
import { users as skillupUsers, userProfiles as skillupUserProfiles, roles as skillupRoles, userRoles as skillupUserRoles } from './packages/db-skillup/src/index';
import bcrypt from 'bcryptjs';
import { eq } from 'drizzle-orm';

async function createTestUsers() {
  console.log('🔧 Creating test users...');

  // RTH User
  try {
    console.log('📍 Checking RTH database connection...');
    
    // Use the exact hash generated by the script
    const rthPasswordHash = '$2b$12$cNd4ybUJu0drHK8Vk53JY.C0U.2bzmKoshoRnvfyEli3EVaDJTTZm';
    
    // Verify the hash works
    const isValidHash = await bcrypt.compare('testing', rthPasswordHash);
    console.log('🔑 RTH password hash verification:', isValidHash ? '✅ VALID' : '❌ INVALID');
    
    // Check if RTH user exists
    const existingRthUser = await rthDb.select().from(users).where(eq(users.email, 'ajayshah@gmail.com')).limit(1);
    
    if (existingRthUser.length === 0) {
      console.log('👤 Creating RTH user: ajayshah@gmail.com');
      
      // Create RTH user
      const [rthUser] = await rthDb.insert(users).values({
        email: 'ajayshah@gmail.com',
        passwordHash: rthPasswordHash,
        emailVerified: true,
        isBlocked: false
      }).returning();

      console.log('✅ RTH user created with ID:', rthUser.id);

      // Create RTH user profile
      await rthDb.insert(userProfiles).values({
        userId: rthUser.id,
        name: 'Ajay Shah'
      });

      console.log('✅ RTH user profile created');

      // Get USER role and assign it
      const userRoles_result = await rthDb.select().from(roles).where(eq(roles.name, 'USER')).limit(1);
      if (userRoles_result.length > 0) {
        await rthDb.insert(userRoles).values({
          userId: rthUser.id,
          roleId: userRoles_result[0].id
        });
        console.log('✅ RTH user role assigned');
      } else {
        console.log('⚠️ USER role not found in RTH database');
      }

      console.log('🎉 RTH user creation completed');
    } else {
      console.log('ℹ️ RTH user already exists with ID:', existingRthUser[0].id);
      
      // Verify password for existing user
      const existingHash = existingRthUser[0].passwordHash;
      const isExistingValid = await bcrypt.compare('testing', existingHash);
      console.log('🔑 Existing RTH user password verification:', isExistingValid ? '✅ VALID' : '❌ INVALID');
    }
  } catch (error) {
    console.error('❌ RTH user creation failed:', error);
  }

  console.log('\n' + '='.repeat(50) + '\n');

  // SkillUp User  
  try {
    console.log('📍 Checking SkillUp database connection...');
    
    // Use the exact hash generated by the script
    const skillupPasswordHash = '$2b$12$iv598PqwDQgtxFO3VS2KE./O3N6PM36NpAg949u2f88LXMkLplfzu';
    
    // Verify the hash works
    const isValidHash = await bcrypt.compare('testing', skillupPasswordHash);
    console.log('🔑 SkillUp password hash verification:', isValidHash ? '✅ VALID' : '❌ INVALID');
    
    // Check if SkillUp user exists
    const existingSkillupUser = await skillupDb.select().from(skillupUsers).where(eq(skillupUsers.email, 'student@skillupitacademy.com')).limit(1);
    
    if (existingSkillupUser.length === 0) {
      console.log('👤 Creating SkillUp user: student@skillupitacademy.com');
      
      // Create SkillUp user
      const [skillupUser] = await skillupDb.insert(skillupUsers).values({
        email: 'student@skillupitacademy.com',
        passwordHash: skillupPasswordHash,
        emailVerified: true,
        isBlocked: false
      }).returning();

      console.log('✅ SkillUp user created with ID:', skillupUser.id);

      // Create SkillUp user profile
      await skillupDb.insert(skillupUserProfiles).values({
        userId: skillupUser.id,
        name: 'SkillUp Student'
      });

      console.log('✅ SkillUp user profile created');

      // Get USER role and assign it
      const userRoles_result = await skillupDb.select().from(skillupRoles).where(eq(skillupRoles.name, 'USER')).limit(1);
      if (userRoles_result.length > 0) {
        await skillupDb.insert(skillupUserRoles).values({
          userId: skillupUser.id,
          roleId: userRoles_result[0].id
        });
        console.log('✅ SkillUp user role assigned');
      } else {
        console.log('⚠️ USER role not found in SkillUp database');
      }

      console.log('🎉 SkillUp user creation completed');
    } else {
      console.log('ℹ️ SkillUp user already exists with ID:', existingSkillupUser[0].id);
      
      // Verify password for existing user
      const existingHash = existingSkillupUser[0].passwordHash;
      const isExistingValid = await bcrypt.compare('testing', existingHash);
      console.log('🔑 Existing SkillUp user password verification:', isExistingValid ? '✅ VALID' : '❌ INVALID');
    }
  } catch (error) {
    console.error('❌ SkillUp user creation failed:', error);
  }

  console.log('\n🏁 Test user creation completed');
  console.log('\n📋 Summary:');
  console.log('- RTH User: ajayshah@gmail.com / testing');
  console.log('- SkillUp User: student@skillupitacademy.com / testing');
  console.log('\n🔧 Next: Test login at:');
  console.log('- https://user.realtutorialhub.com/login');
  console.log('- https://user.skillupitacademy.com/login');
}

// Handle errors gracefully
createTestUsers().catch((error) => {
  console.error('💥 Script failed:', error);
  process.exit(1);
});