packages:
  - "apps/*"
  - "apps/realtutorialhub-admin"
  - "apps/realtutorialhub-quiz"
  - "apps/skillup-web"
  - "apps/skillup-admin"
  - "apps/faculty-app"
  - "apps/skillhubcore-admin"
  - "services/api-gateway"
  - "packages/*"
  - "services/*"
