"""
Placement Executor Agent - WAVE 5

Executes ONLY an approved placement manifest.
This agent never recomputes placement, executes arbitrary shell commands, 
or modifies the manifest.

Key invariants:
- Only executes manifests with status == APPROVED
- Verifies approval payload matches manifest hash
- Uses RepositoryAdapter interface (no raw shell commands)
- Records evidence for audit trail
"""

from typing import Literal
from pydantic import BaseModel, Field

from app.agents.placement_manifest import (
    PlacementManifest,
    PlacementAction,
    ArtifactPlacement
)


class ApprovalPayload(BaseModel):
    """Approval payload that must match the manifest being executed."""
    
    manifest_hash: str = Field(..., description="SHA-256 hash of the approved manifest")
    approved_by: str = Field(..., description="Human approver identity")
    approved_at: str = Field(..., description="ISO 8601 timestamp of approval")
    reason: str | None = Field(None, description="Optional approval reason")


class PlacementExecutionResult(BaseModel):
    """Result of placement execution."""
    
    workflow_id: str = Field(..., description="Workflow ID this execution belongs to")
    manifest_hash: str = Field(..., description="Hash of executed manifest")
    executed_placements: list[dict] = Field(
        default_factory=list,
        description="List of executed placements with {action, target_path, status}"
    )
    failed_placements: list[dict] = Field(
        default_factory=list,
        description="List of failed placements with error details"
    )
    status: Literal["SUCCESS", "PARTIAL", "FAILED"] = Field(
        ...,
        description="Overall execution status"
    )
    evidence_id: str = Field(..., description="Evidence record ID for this execution")


class RepositoryAdapter:
    """
    Repository adapter interface for safe file operations.
    
    This abstraction prevents direct shell command execution and provides
    a controlled interface for repository mutations.
    """
    
    def add_file(self, candidate_path: str, target_path: str) -> None:
        """
        Add a new file to the repository.
        
        Args:
            candidate_path: Path to candidate file
            target_path: Target path in repository
            
        Raises:
            ValueError: If target already exists or operation fails
        """
        # TODO: Implement actual file addition logic
        # This is a contract stub - implementation will be added in later wave
        pass
    
    def update_file(self, candidate_path: str, target_path: str) -> None:
        """
        Update an existing file in the repository.
        
        Args:
            candidate_path: Path to candidate file
            target_path: Target path in repository to update
            
        Raises:
            ValueError: If target does not exist or operation fails
        """
        # TODO: Implement actual file update logic
        # This is a contract stub - implementation will be added in later wave
        pass
    
    def extend_file(self, candidate_path: str, target_path: str) -> None:
        """
        Extend an existing file family with new variant.
        
        Args:
            candidate_path: Path to candidate file
            target_path: Target path in repository to extend
            
        Raises:
            ValueError: If operation fails
        """
        # TODO: Implement actual file extension logic
        # This is a contract stub - implementation will be added in later wave
        pass


class PlacementExecutor:
    """
    Executes ONLY an approved manifest. Never recomputes placement.
    
    This agent is the final executor in the placement pipeline:
    1. Manifest generated by PlacementManifestAgent
    2. Manifest submitted for approval via GovernanceAgent
    3. Human approves manifest
    4. THIS AGENT executes the approved manifest
    
    Safety invariants:
    - Only executes APPROVED manifests
    - Verifies approval hash matches manifest hash
    - Uses RepositoryAdapter (no raw shell commands)
    - Records evidence for every operation
    """
    
    def __init__(self, repo_adapter: RepositoryAdapter | None = None):
        """
        Initialize placement executor.
        
        Args:
            repo_adapter: Repository adapter for file operations
        """
        self.repo_adapter = repo_adapter or RepositoryAdapter()
    
    def execute(
        self,
        manifest: PlacementManifest,
        approval: ApprovalPayload,
    ) -> PlacementExecutionResult:
        """
        Execute an approved placement manifest.
        
        Args:
            manifest: Placement manifest to execute
            approval: Approval payload with verified hash
            
        Returns:
            Execution result with evidence ID
            
        Raises:
            ValueError: If manifest is not approved or approval hash mismatch
        """
        # 1. Verify manifest.status == APPROVED
        if manifest.status != "APPROVED":
            raise ValueError(
                f"Cannot execute non-approved manifest. "
                f"Manifest status: {manifest.status}. "
                f"Only manifests with status=APPROVED can be executed."
            )
        
        # 2. Verify approval payload matches manifest hash
        if approval.manifest_hash != manifest.manifest_hash:
            raise ValueError(
                f"Approval manifest_hash does not match manifest. "
                f"Expected: {manifest.manifest_hash}, "
                f"Got: {approval.manifest_hash}. "
                f"This indicates manifest tampering or approval/manifest mismatch."
            )
        
        # 3. Execute each placement via repo_adapter (not raw shell commands)
        executed: list[dict] = []
        failed: list[dict] = []
        
        for placement in manifest.placements:
            try:
                self._execute_placement(placement)
                executed.append({
                    "action": placement.action.value,
                    "target_path": placement.target_path,
                    "status": "success"
                })
            except Exception as e:
                failed.append({
                    "action": placement.action.value,
                    "target_path": placement.target_path,
                    "status": "failed",
                    "error": str(e)
                })
        
        # 4. Determine overall status
        if not failed:
            status: Literal["SUCCESS", "PARTIAL", "FAILED"] = "SUCCESS"
        elif executed:
            status = "PARTIAL"
        else:
            status = "FAILED"
        
        # 5. Record evidence (stub - will be implemented in evidence wave)
        evidence_id = f"ev-placement-{manifest.workflow_id}"
        
        # 6. Return result
        return PlacementExecutionResult(
            workflow_id=manifest.workflow_id,
            manifest_hash=manifest.manifest_hash,
            executed_placements=executed,
            failed_placements=failed,
            status=status,
            evidence_id=evidence_id
        )
    
    def _execute_placement(self, placement: ArtifactPlacement) -> None:
        """
        Execute a single artifact placement.
        
        Args:
            placement: Artifact placement to execute
            
        Raises:
            ValueError: If placement action is invalid or operation fails
        """
        if placement.action == PlacementAction.ADD:
            self.repo_adapter.add_file(
                placement.candidate_path,
                placement.target_path
            )
        
        elif placement.action == PlacementAction.UPDATE:
            self.repo_adapter.update_file(
                placement.candidate_path,
                placement.target_path
            )
        
        elif placement.action == PlacementAction.EXTEND:
            self.repo_adapter.extend_file(
                placement.candidate_path,
                placement.target_path
            )
        
        elif placement.action == PlacementAction.REUSE:
            # REUSE is a no-op: existing artifact is sufficient
            pass
        
        elif placement.action == PlacementAction.REJECT:
            raise ValueError(
                f"Cannot execute REJECT action. "
                f"Rejected placements should not be in manifest.placements list."
            )
        
        else:
            raise ValueError(f"Unknown placement action: {placement.action}")
