name = "platform-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "api.realtutorialhub.com/*"
zone_name = "realtutorialhub.com"

[[env.production.routes]]
pattern = "api.skillhubcore.in/*"
zone_name = "skillhubcore.in"
