name = "platform-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production", SKILLUP_WEB_URL = "https://skillup-web-plldp3atca-el.a.run.app", SKILLUP_ADMIN_URL = "https://skillup-admin-plldp3atca-el.a.run.app", FACULTY_URL = "https://faculty-app-plldp3atca-el.a.run.app", SKILLHUBCORE_URL = "https://skillhubcore-service-plldp3atca-el.a.run.app" }

[[env.production.routes]]
pattern = "api.realtutorialhub.com/*"
zone_name = "realtutorialhub.com"

[[env.production.routes]]
pattern = "api.skillhubcore.in/*"
zone_name = "skillhubcore.in"
