import type { ContentAnalysisResult } from '@quiz/types';

export const mockContentAnalysisResult: ContentAnalysisResult = {
  documentId: 'doc-js-intro-001',
  subtopicId: '00000000-0000-0000-0000-000000000001',
  statistics: {
    totalWords: 612,
    characters: 3742,
    readingTimeMinutes: 2,
    sectionsDetected: 6,
    totalBlocks: 18,
    sectionsBreakdown: 'H1: 1, H2: 5, H3: 2',
  },
  sectionOutline: [
    {
      id: 'sec-1',
      level: 'h1',
      title: 'JavaScript',
      snippet: 'JavaScript is a programming language that makes websites interactive. While HTML gives a webpage...',
      confidence: 99,
      isVerified: true,
    },
    {
      id: 'sec-2',
      level: 'h2',
      title: '1. What does it actually do? (The "Interactive" Part)',
      snippet: 'When you click a button and a menu drops down, when you see live stock tickers update...',
      confidence: 95,
      isVerified: true,
    },
    {
      id: 'sec-3',
      level: 'h2',
      title: '2. Where does it run? (The Two Sides)',
      snippet: 'JavaScript is no longer just a "web browser" language:',
      confidence: 92,
      isVerified: true,
      subsections: [
        {
          id: 'sec-3a',
          level: 'h3',
          title: 'Client-Side (Frontend)',
          snippet: 'This is its original home. The JavaScript code is sent to your web browser...',
          confidence: 93,
          isVerified: true,
        },
        {
          id: 'sec-3b',
          level: 'h3',
          title: 'Server-Side (Backend)',
          snippet: 'Thanks to a runtime environment called Node.js, JavaScript can now run on web servers...',
          confidence: 90,
          isVerified: true,
        },
      ],
    },
    {
      id: 'sec-4',
      level: 'h2',
      title: '3. Key Technical Characteristics (The "Nerdy" Bits)',
      snippet: 'To understand what it is, it helps to know its core traits:',
      confidence: 90,
      isVerified: true,
    },
    {
      id: 'sec-5',
      level: 'h2',
      title: '4. The JavaScript Ecosystem (Frameworks)',
      snippet: 'Very rarely do developers write plain, raw JavaScript anymore...',
      confidence: 88,
      isVerified: true,
    },
    {
      id: 'sec-6',
      level: 'h2',
      title: '5. The Crucial Clarification: JavaScript is NOT Java',
      snippet: 'Despite the similar name, they are completely different languages...',
      confidence: 95,
      isVerified: true,
    },
    {
      id: 'sec-7',
      level: 'summary',
      title: 'Summary',
      snippet: 'Today, JavaScript is the undisputed "language of the web." According to Stack Overflow...',
      confidence: 91,
      isVerified: true,
    },
  ],
  qualityIndicators: {
    readability: 'good',
    structure: 'excellent',
    completeness: 'good',
    examples: 'fair',
    codePresence: 'none',
    visualPotential: 'high',
  },
  smartSuggestions: [
    {
      id: 'sug-1',
      text: 'Section 2 has two parallel concepts (Client-Side and Server-Side). Consider a two-column layout.',
      type: 'layout',
      targetSectionId: 'sec-3',
    },
    {
      id: 'sug-2',
      text: 'Section 3 lists key characteristics. A concept card or grid layout may work well.',
      type: 'component',
      targetSectionId: 'sec-4',
    },
    {
      id: 'sug-3',
      text: 'Section 4 lists ecosystem areas. Card layout with icons is recommended.',
      type: 'layout',
      targetSectionId: 'sec-5',
    },
    {
      id: 'sug-4',
      text: 'Consider adding a summary callout at the end for better retention.',
      type: 'callout',
      targetSectionId: 'sec-7',
    },
  ],
  detectedElements: {
    headings: 8,
    paragraphs: 7,
    bulletLists: 3,
    numberedLists: 0,
    codeBlocks: 0,
    quotes: 1,
    tables: 0,
    callouts: 1,
    keyConcepts: 4,
    comparisons: 1,
    examples: 1,
  },
  overallConfidence: {
    score: 87,
    grade: 'Good',
    description: 'High confidence in structure detection. Review suggestions before proceeding.',
  },
};
