"""
Certification Models.

Final certification verdict and human certification workflow.
"""

from dataclasses import dataclass
from typing import List, Dict, Any, Optional
from enum import Enum


class CertificationVerdict(str, Enum):
    """Final certification verdict."""
    CERTIFICATION_READY = "CERTIFICATION_READY"  # All gates passed
    BLOCKED = "BLOCKED"  # Missing evidence or prerequisites
    FAIL = "FAIL"  # Gate failures
    PASS = "PASS"  # No gates to verify (minimal certification)


class HumanCertificationDecision(str, Enum):
    """Human certification decision."""
    CERTIFIED = "CERTIFIED"
    REJECTED = "REJECTED"
    PENDING = "PENDING"


@dataclass
class FinalCertification:
    """
    Final certification record.
    
    Generated by Agent 14 (Final Gate Controller).
    Reviewed by Agent 15 (Human Certification).
    
    Aggregates:
    - All gate results (12A-12J)
    - Evidence binding validation
    - Commit + snapshot hash
    - Final verdict
    """
    
    certification_id: str
    run_id: str
    candidate_id: str
    
    # Metadata
    commit_sha: str
    snapshot_hash: str
    
    # Gate results
    gate_results: List[Dict[str, Any]]  # List of GateResult dicts
    
    # Evidence validation
    all_evidence_ids: List[str]
    evidence_binding_valid: bool
    evidence_binding_errors: List[str]
    
    # Verdict
    verdict: CertificationVerdict
    verdict_reasoning: str
    
    # Human certification
    human_decision: HumanCertificationDecision
    
    # Metadata
    generated_at: str
    generated_by_agent: str  # "final-gate-controller"
    
    # Optional human certification fields
    human_reviewer: Optional[str] = None
    human_review_at: Optional[str] = None
    human_comments: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            'certification_id': self.certification_id,
            'run_id': self.run_id,
            'candidate_id': self.candidate_id,
            'commit_sha': self.commit_sha,
            'snapshot_hash': self.snapshot_hash,
            'gate_results': self.gate_results,
            'all_evidence_ids': self.all_evidence_ids,
            'evidence_binding_valid': self.evidence_binding_valid,
            'evidence_binding_errors': self.evidence_binding_errors,
            'verdict': self.verdict.value,
            'verdict_reasoning': self.verdict_reasoning,
            'human_decision': self.human_decision.value,
            'human_reviewer': self.human_reviewer,
            'human_review_at': self.human_review_at,
            'human_comments': self.human_comments,
            'generated_at': self.generated_at,
            'generated_by_agent': self.generated_by_agent
        }
