"""
Evidence Record Model

Maps TypeScript Evidence interface to Python dataclass for evidence logging.

Architecture Rule: Evidence IDs ONLY come from TypeScript snapshot.
Python NEVER generates evidence IDs.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, Optional


@dataclass
class EvidenceRecord:
    """
    Evidence record from TypeScript snapshot.
    
    Matches the TypeScript Evidence interface exactly:
    - evidenceId: Deterministic ID generated by TypeScript (evidence-{hash})
    - scannerName: D1-D6 scanner that generated evidence
    - timestamp: ISO 8601 timestamp
    - path: Normalized repository path
    - kind: Evidence kind (20+ types)
    - claim: Human-readable claim
    - locator: File or directory locator
    - contentHash: SHA-256 hash of content
    - lifecycle: 'current' or 'historical'
    - symbol: Optional disambiguator
    - metadata: Additional metadata
    """
    
    evidence_id: str
    scanner_name: str
    timestamp: str
    path: str
    kind: str
    claim: str
    locator: str
    content_hash: str
    lifecycle: str
    symbol: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    @classmethod
    def from_snapshot(cls, record: Dict[str, Any]) -> 'EvidenceRecord':
        """
        Parse evidence record from TypeScript snapshot JSON.
        
        Args:
            record: Evidence object from snapshot['evidence'] array
            
        Returns:
            EvidenceRecord instance
            
        Raises:
            KeyError: If required fields missing
        """
        return cls(
            evidence_id=record['evidenceId'],
            scanner_name=record['scannerName'],
            timestamp=record['timestamp'],
            path=record['path'],
            kind=record['kind'],
            claim=record['claim'],
            locator=record['locator'],
            content_hash=record['contentHash'],
            lifecycle=record['lifecycle'],
            symbol=record.get('symbol'),
            metadata=record.get('metadata', {})
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for JSON serialization.
        
        Returns:
            Dictionary with camelCase keys matching TypeScript
        """
        result = {
            'evidenceId': self.evidence_id,
            'scannerName': self.scanner_name,
            'timestamp': self.timestamp,
            'path': self.path,
            'kind': self.kind,
            'claim': self.claim,
            'locator': self.locator,
            'contentHash': self.content_hash,
            'lifecycle': self.lifecycle,
        }
        
        if self.symbol is not None:
            result['symbol'] = self.symbol
            
        if self.metadata:
            result['metadata'] = self.metadata
            
        return result
