"""
Placement Models.

Defines placement manifest, placement entries, and execution results.
Extends PlacementManifest from candidate.py with additional fields.
"""

from dataclasses import dataclass
from typing import List, Optional
from enum import Enum


class PlacementAction(str, Enum):
    """Placement action types."""
    ADD = "ADD"
    UPDATE = "UPDATE"
    EXTEND = "EXTEND"
    REUSE = "REUSE"
    REJECT = "REJECT"


@dataclass
class PlacementEntry:
    """
    A single file placement operation.
    
    Specifies:
    - Source file from candidate package
    - Target path in repository
    - Operation type (create, update, merge)
    - Conflict resolution strategy
    """
    
    entry_id: str
    source_file: str  # Relative to candidate package
    target_path: str  # Absolute repository path
    operation: str  # 'create', 'update', 'merge'
    conflict_strategy: str  # 'overwrite', 'skip', 'manual'
    backup_path: Optional[str] = None


@dataclass
class PlacementManifest:
    """
    Complete placement manifest for a candidate block.
    
    Generated by Agent 08 (Placement Manifest).
    Approved by Agent 09 (Human Approval).
    Executed by Agent 10 (Placement Executor).
    
    ARCHITECTURAL RULE:
    - Target paths NEVER inferred from candidate block names
    - Manifest hash provides tamper detection
    - Human approval binds to manifest hash
    
    NOTE: This extends the PlacementManifest from candidate.py with additional fields
    required by the 15-agent DAG architecture.
    """
    
    manifest_id: str
    candidate_id: str
    action: PlacementAction
    target_path: str  # Repository path (e.g., "packages/blocks/introduction/I3")
    block_family: str
    block_version: str  # UBRC-compliant version
    
    # File operations
    entries: List[PlacementEntry]
    
    # Requirements
    required_changes: List[str]
    
    # Evidence binding
    evidence_ids: List[str]
    snapshot_hash: str
    commit_sha: str
    
    # Tamper detection
    manifest_hash: str  # SHA-256 of manifest content
    
    # Approval
    approval_status: str  # ApprovalStatus value
    
    # Metadata
    created_at: str
    created_by_agent: str  # "placement-manifest"
    
    # Optional approval fields
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None
    approval_manifest_hash: Optional[str] = None  # Hash at approval time


@dataclass
class PlacementExecutionResult:
    """Result of placement execution (Agent 10 output)."""
    manifest_id: str
    success: bool
    files_created: List[str]
    files_updated: List[str]
    files_skipped: List[str]
    errors: List[str]
    rollback_available: bool
    execution_time_ms: float
