"""
Candidate Block Specification Models.

Agent 04: Block Specification generates CandidateBlockSpecification
from analyzed candidate files and repository context.
"""

from dataclasses import dataclass
from typing import List, Optional
from enum import Enum


class SpecificationStatus(str, Enum):
    """Status of specification generation."""
    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"
    INVALID = "INVALID"


@dataclass
class StructuralRequirement:
    """A structural requirement extracted from canonical blocks."""
    requirement_id: str
    category: str  # 'rendering', 'state', 'props', 'styling', 'behavior'
    description: str
    canonical_evidence_id: str
    mandatory: bool


@dataclass
class CandidateBlockSpecification:
    """
    Complete specification for a candidate block.
    
    Generated by Agent 04 (Block Specification) after:
    - Agent 01 audits repository
    - Agent 02 freezes snapshot
    - Agent 03 freezes evidence
    
    This specification defines:
    - What the candidate block IS (structure, props, behavior)
    - What family it belongs to (Introduction, Tutorial, etc.)
    - What requirements it must meet (structural, UBRC, brand, theme)
    - What evidence supports these determinations
    """
    
    specification_id: str
    candidate_id: str
    block_family: str  # BlockFamily value
    detected_type: str  # Specific block type (e.g., "I1", "I2")
    
    # Structural analysis
    file_count: int
    has_typescript: bool
    has_styles: bool
    has_tests: bool
    component_names: List[str]
    
    # Requirements derived from canonical blocks
    structural_requirements: List[StructuralRequirement]
    
    # Evidence binding
    evidence_ids: List[str]  # From TypeScript discovery
    snapshot_hash: str
    commit_sha: str
    
    # Status
    status: SpecificationStatus
    warnings: List[str]
    
    # Metadata
    created_at: str  # ISO 8601
    created_by_agent: str  # "block-specification"


@dataclass
class SpecificationResult:
    """Result of specification generation (Agent 04 output)."""
    specification: Optional[CandidateBlockSpecification]
    status: str  # SUCCESS, FAILED, BLOCKED
    errors: List[str]
    execution_time_ms: float
