ALTER TABLE "project_ai_approvals" ALTER COLUMN "approval_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "workflow_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "candidate_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "placement_manifest_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "placement_manifest_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "target_family" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "target_version" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "approved_by" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "workflow_requester" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "candidate_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "workflow_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "uploaded_by" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "target_family" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "target_version" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "candidate_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "workflow_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_hash" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_version" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_version" SET DEFAULT '1.0';--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "manifest_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "candidate_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "manifest_hash" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "decision" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "target_path" SET DATA TYPE varchar(500);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "block_family" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "block_version" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "workflow_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "from_state" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "to_state" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "triggered_by" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "evidence_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "workflow_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "specification_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "target_family" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "target_version" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "requester_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "current_state" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "contract_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "contract_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "candidate_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "candidate_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "manifest_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "manifest_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "snapshot_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "snapshot_sha256" SET DATA TYPE varchar(64);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "approval_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "final_status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "idempotency_key" SET DATA TYPE varchar(255);