-- Convert varchar primary keys to UUID with explicit USING clause
-- This migration corrects FEAT-001 schema to use proper UUID types

-- 1. Drop all foreign key constraints (handle all possible constraint names)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT conname, conrelid::regclass AS table_name
        FROM pg_constraint
        WHERE contype = 'f'
          AND (conrelid::regclass::text LIKE '%project_ai%' 
               OR confrelid::regclass::text LIKE '%project_ai%')
    LOOP
        EXECUTE 'ALTER TABLE ' || r.table_name || ' DROP CONSTRAINT IF EXISTS ' || quote_ident(r.conname);
    END LOOP;
END $$;--> statement-breakpoint

-- 2. Convert project_ai_workflows columns to UUID
ALTER TABLE "project_ai_workflows" ALTER COLUMN "workflow_id" SET DATA TYPE uuid USING workflow_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "workflow_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "specification_id" SET DATA TYPE uuid USING specification_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "contract_id" SET DATA TYPE uuid USING contract_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "candidate_id" SET DATA TYPE uuid USING candidate_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "manifest_id" SET DATA TYPE uuid USING manifest_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "snapshot_id" SET DATA TYPE uuid USING snapshot_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_workflows" ALTER COLUMN "approval_id" SET DATA TYPE uuid USING approval_id::uuid;--> statement-breakpoint

-- 3. Convert project_ai_state_transitions columns to UUID
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "workflow_id" SET DATA TYPE uuid USING workflow_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_state_transitions" ALTER COLUMN "evidence_id" SET DATA TYPE uuid USING evidence_id::uuid;--> statement-breakpoint

-- 4. Convert project_ai_contracts columns to UUID
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_id" SET DATA TYPE uuid USING contract_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "contract_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ALTER COLUMN "workflow_id" SET DATA TYPE uuid USING workflow_id::uuid;--> statement-breakpoint

-- 5. Convert project_ai_candidates columns to UUID
ALTER TABLE "project_ai_candidates" ALTER COLUMN "candidate_id" SET DATA TYPE uuid USING candidate_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "candidate_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ALTER COLUMN "workflow_id" SET DATA TYPE uuid USING workflow_id::uuid;--> statement-breakpoint

-- 6. Convert project_ai_manifests columns to UUID
ALTER TABLE "project_ai_manifests" ALTER COLUMN "manifest_id" SET DATA TYPE uuid USING manifest_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "manifest_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ALTER COLUMN "candidate_id" SET DATA TYPE uuid USING candidate_id::uuid;--> statement-breakpoint

-- 7. Convert project_ai_approvals columns to UUID
ALTER TABLE "project_ai_approvals" ALTER COLUMN "approval_id" SET DATA TYPE uuid USING approval_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "approval_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "workflow_id" SET DATA TYPE uuid USING workflow_id::uuid;--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ALTER COLUMN "placement_manifest_id" SET DATA TYPE uuid USING placement_manifest_id::uuid;--> statement-breakpoint

-- 8. Recreate foreign key constraints
ALTER TABLE "project_ai_state_transitions" ADD CONSTRAINT "fk_state_transitions_workflow_id" FOREIGN KEY ("workflow_id") REFERENCES "project_ai_workflows"("workflow_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "project_ai_contracts" ADD CONSTRAINT "fk_contracts_workflow_id" FOREIGN KEY ("workflow_id") REFERENCES "project_ai_workflows"("workflow_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "project_ai_candidates" ADD CONSTRAINT "fk_candidates_workflow_id" FOREIGN KEY ("workflow_id") REFERENCES "project_ai_workflows"("workflow_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "project_ai_manifests" ADD CONSTRAINT "fk_manifests_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "project_ai_candidates"("candidate_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "project_ai_approvals" ADD CONSTRAINT "fk_approvals_workflow_id" FOREIGN KEY ("workflow_id") REFERENCES "project_ai_workflows"("workflow_id") ON DELETE CASCADE;
